// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpbk_D_lR0KOsJ6hi3Vs4OJeu_qszKGPA',
    appId: '1:13506456776:web:db00fc00bb7061100289fd',
    messagingSenderId: '13506456776',
    projectId: 'dharati-48157',
    authDomain: 'dharati-48157.firebaseapp.com',
    storageBucket: 'dharati-48157.appspot.com',
    measurementId: 'G-C1CQEJWDJ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbxaxB8-lAE2mr4MeORNbBTXWeuiWC1Rk',
    appId: '1:13506456776:android:1be8702b6d0cdba80289fd',
    messagingSenderId: '13506456776',
    projectId: 'dharati-48157',
    storageBucket: 'dharati-48157.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASqU06tk53RIeG3Qud2ebvLVl81PgewUE',
    appId: '1:13506456776:ios:6233dc65a07c9d7b0289fd',
    messagingSenderId: '13506456776',
    projectId: 'dharati-48157',
    storageBucket: 'dharati-48157.appspot.com',
    androidClientId: '13506456776-1qrbpdojrc0od1ff2l9ega382seh4p9p.apps.googleusercontent.com',
    iosClientId: '13506456776-dl3l2dlnoi394fqg9r06gb2pbh773r3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.dharati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASqU06tk53RIeG3Qud2ebvLVl81PgewUE',
    appId: '1:13506456776:ios:6233dc65a07c9d7b0289fd',
    messagingSenderId: '13506456776',
    projectId: 'dharati-48157',
    storageBucket: 'dharati-48157.appspot.com',
    androidClientId: '13506456776-1qrbpdojrc0od1ff2l9ega382seh4p9p.apps.googleusercontent.com',
    iosClientId: '13506456776-dl3l2dlnoi394fqg9r06gb2pbh773r3b.apps.googleusercontent.com',
    iosBundleId: 'com.example.dharati',
  );
}
