// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHhZNEgFHmSBkpIvasEC4gCZx3-nQApKM',
    appId: '1:327649660070:web:3a2a4a5fd629d19277f867',
    messagingSenderId: '327649660070',
    projectId: 'krushee-sanskrutee',
    authDomain: 'krushee-sanskrutee.firebaseapp.com',
    storageBucket: 'krushee-sanskrutee.appspot.com',
    measurementId: 'G-NZ6N0HT88S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLdiefdPNzQEIiOkJrEdjIlxawWIYP5jA',
    appId: '1:327649660070:android:c14c79f963fba3bf77f867',
    messagingSenderId: '327649660070',
    projectId: 'krushee-sanskrutee',
    storageBucket: 'krushee-sanskrutee.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQellfEbBWsCc6H9dVdAi8j8qLG71Azkg',
    appId: '1:327649660070:ios:ee5bc42838613b8377f867',
    messagingSenderId: '327649660070',
    projectId: 'krushee-sanskrutee',
    storageBucket: 'krushee-sanskrutee.appspot.com',
    androidClientId: '327649660070-0vrv335tjqj5jb9ivbi2n67s4ascprmv.apps.googleusercontent.com',
    iosClientId: '327649660070-13tkgdmmcobhh3uj2l0pmv7vdvhjvk7e.apps.googleusercontent.com',
    iosBundleId: 'com.saffronedgetech.krusheesanskrutee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQellfEbBWsCc6H9dVdAi8j8qLG71Azkg',
    appId: '1:327649660070:ios:ee5bc42838613b8377f867',
    messagingSenderId: '327649660070',
    projectId: 'krushee-sanskrutee',
    storageBucket: 'krushee-sanskrutee.appspot.com',
    androidClientId: '327649660070-0vrv335tjqj5jb9ivbi2n67s4ascprmv.apps.googleusercontent.com',
    iosClientId: '327649660070-13tkgdmmcobhh3uj2l0pmv7vdvhjvk7e.apps.googleusercontent.com',
    iosBundleId: 'com.saffronedgetech.krusheesanskrutee',
  );
}
