// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ_E9yeCAk6PVJgHDm7oPPOKz8LxjB59k',
    appId: '1:524024832715:web:e9117868bdd79ff184314e',
    messagingSenderId: '524024832715',
    projectId: 'dharati-cb793',
    authDomain: 'dharati-cb793.firebaseapp.com',
    storageBucket: 'dharati-cb793.appspot.com',
    measurementId: 'G-7VHHDBKRQK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLL22w5JABNzdRLV1akCLKPRuFj5koWi0',
    appId: '1:524024832715:android:d103e1d88523934784314e',
    messagingSenderId: '524024832715',
    projectId: 'dharati-cb793',
    storageBucket: 'dharati-cb793.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9Bl0BAZQBdRmIBKKz1yfdlVoiPpCZPWk',
    appId: '1:524024832715:ios:1b22c449e60aee5584314e',
    messagingSenderId: '524024832715',
    projectId: 'dharati-cb793',
    storageBucket: 'dharati-cb793.appspot.com',
    androidClientId: '524024832715-2tqsdnb47tkn6345803v9kqvnriko6a9.apps.googleusercontent.com',
    iosClientId: '524024832715-2l6nqg1epb7sp816i0mjsrh3aisns9nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dharati',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9Bl0BAZQBdRmIBKKz1yfdlVoiPpCZPWk',
    appId: '1:524024832715:ios:1b22c449e60aee5584314e',
    messagingSenderId: '524024832715',
    projectId: 'dharati-cb793',
    storageBucket: 'dharati-cb793.appspot.com',
    androidClientId: '524024832715-2tqsdnb47tkn6345803v9kqvnriko6a9.apps.googleusercontent.com',
    iosClientId: '524024832715-2l6nqg1epb7sp816i0mjsrh3aisns9nd.apps.googleusercontent.com',
    iosBundleId: 'com.example.dharati',
  );
}
